/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hujiang_crashcapture_NativeCrashCapture */

#ifndef _Included_com_hujiang_crashcapture_NativeCrashCapture
#define _Included_com_hujiang_crashcapture_NativeCrashCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hujiang_crashcapture_NativeCrashCapture
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hujiang_crashcapture_NativeCrashCapture_nativeInit
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
